// Data for sections
window.HC_DATA = {
  eventos: [
    {
      id: "e1",
      day: "12",
      month: "Nov",
      kind: "Mesa redonda",
      title: "Cocina a baja temperatura con Gorka Mota",
      time: "17:00h — 20:00h",
      place: "Mercado de Vallehermoso",
      format: "Presencial",
      attendees: 32,
      photo: "assets/evento-1.png",
      isFree: false,
    },
    {
      id: "e2",
      day: "23",
      month: "Nov",
      kind: "Festival",
      title: "Bakea",
      time: "10:00h — 13:00h",
      place: "Mungia, Bizkaia",
      format: "Presencial",
      attendees: 15,
      photo: "assets/evento-2.png",
      isFree: false,
    },
    {
      id: "e3",
      day: "04",
      month: "Dic",
      kind: "Encuentro",
      title: "El producto como clave del éxito",
      time: "11:00h — 18:00h",
      place: "Mercado de Vallehermoso",
      format: "Presencial",
      attendees: 33,
      photo: "assets/evento-3.png",
      isFree: false,
    },
  ],
  podcasts: [
    { id: "p1", title: "Sara Aznar y Nacho Ventosa, Los 33", ep: "01", date: "Oct 7", dur: "01:05:22", isNew: false, art: "assets/podcast-1.png" },
    { id: "p2", title: "Lucía Freitas, A Tafona", ep: "02", date: "Oct 14", dur: "00:58:11", isNew: false, art: "assets/podcast-2.png" },
    { id: "p3", title: "Javier Zanz y Juan Sahuquillo, Cañitas Maite", ep: "03", date: "Oct 21", dur: "01:12:04", isNew: false, art: "assets/podcast-3.png" },
    { id: "p4", title: "Don Panko, David de la Torre", ep: "04", date: "Oct 28", dur: "01:02:48", isNew: false, art: "assets/podcast-4.png" },
    { id: "p5", title: "Abarike, Lara Rodríguez", ep: "05", date: "Nov 4", dur: "00:54:30", isNew: false, art: "assets/podcast-5.png" },
    { id: "p6", title: "Lula y la Herradura, Aurora Torres", ep: "06", date: "Nov 11", dur: "01:08:55", isNew: false, art: "assets/podcast-6.png" },
  ],
  pildoras: [
    { id: "pl1", cat: "Gestión", title: "Tratamiento, despiece y conservación de aves.", author: "Laura Vázquez", dur: "1:32", photo: "assets/pildora-1.png" },
    { id: "pl2", cat: "Sala", title: "“El trabajo de la mujer en la cocina siempre ha sido silenciado”", author: "Marcos Reig", dur: "1:18", photo: "assets/pildora-2.png" },
    { id: "pl3", cat: "Equipo", title: "Más allá de la cocina: La gestión del éxito.", author: "Juanjo López", dur: "1:45", photo: "assets/pildora-3.png" },
    { id: "pl4", cat: "Cocina", title: "El ingrediente secreto es \nla confianza en las personas.", author: "Carlos Zamora", dur: "1:28", photo: "assets/pildora-4.png" },
    { id: "pl5", cat: "Marketing", title: "Una foto de plato bien hecha con el móvil", author: "Sofía Pereda", dur: "1:11", photo: "assets/pildora-5.png" },
  ],
  herramientas: [
    { id: "h1", overline: "Fandit", title: "Ayudas y subvenciones", style: "default", logo: "assets/logo-fandit.png" },
    { id: "h5", overline: "Shifty", title: "Encuentra personal", style: "default", logo: "assets/logo-shifty.png" },
    { id: "h6", overline: "Tipi", title: "Conoce el beneficio de tu plato", style: "default", logo: "assets/logo-tipi.png" },
    { id: "h2", overline: "Gestión de reseñas", title: "Controla lo que dicen de tu restaurante", style: "default", icon: "chart" },
    { id: "h3", overline: "Calculadora CAEs", title: "Ahorra en tu factura energética", style: "default", icon: "sparkle" },
    { id: "h4", overline: "Generador de QR", title: "Crea el QR de tu carta y wifi", style: "default", icon: "qr" },
  ],
  formaciones: [
    {
      id: "f1",
      cat: "Gestión eficiente",
      title: "Gestión eficiente para que los números cuadren",
      desc: "Olvídate de los excels que no entiendes. Aquí aprenderás a controlar el escandallo, a negociar con proveedores y a entender dónde se te escapa el dinero. Pura gestión, sin rodeos.",
      date: "02 oct 2025",
      duration: "1h",
      format: "Online",
      seats: { total: 80, taken: 62 },
      isFree: true,
    },
    {
      id: "f2",
      cat: "Equipos y formación",
      title: "Manual para liderar a tu equipo",
      desc: "El talento se va, la gente no se motiva, los fuegos no paran. Esta formación te da las herramientas para crear un equipo que se quede, que rinda y que crea en tu proyecto. Menos dramas, más piña.",
      date: "24 oct 2025",
      duration: "2h",
      format: "Online",
      seats: { total: 60, taken: 28 },
      isFree: true,
    },
    {
      id: "f3",
      cat: "Marketing",
      title: "El local lleno: marketing que, de verdad, funciona",
      desc: "Deja de tirar el dinero en anuncios que no sirven. Aprende a usar las redes sociales, a crear una base de datos de clientes y a contar la historia que hará que la gente haga cola en tu puerta.",
      date: "05 nov 2025",
      duration: "2h",
      format: "Presencial",
      seats: { total: 30, taken: 27 },
      isFree: false,
    },
  ],
  articulos: [
    {
      id: "a1",
      cat: "Oferta gastronómica",
      title: "¿Cómo sacarle el máximo partido a los galardonados de Repsol en redes sociales?",
      excerpt: "Haz que tus galardones brillen en el mundo digital",
      author: "Marta Sahelices",
      read: "3 min",
      date: "8 nov 2025",
      photo: "assets/articulo-1.png",
    },
    {
      id: "a2",
      cat: "Historias de la calle",
      title: "Cómo mejorar la reputación digital de tu negocio",
      excerpt: "Sabemos que llevar un negocio de hostelería significa estar en todo: barra, sala, cocina, gestión… Pero hay algo que no puedes dejar de lado: tu reputación digital.",
      author: "Carlos Maribona",
      read: "3 min",
      date: "5 nov 2025",
      photo: "assets/articulo-2.png",
    },
    {
      id: "a3",
      cat: "Gestión eficiente",
      title: "Cómo hacer una carta de alérgenos: normativa y consejos",
      excerpt: "Aprende cómo hacer una carta de alérgenos para tu restaurante, cumple la normativa UE, evita sanciones y mejora la seguridad y confianza de tus clientes.",
      author: "Bea Mateos",
      read: "3 min",
      date: "2 nov 2025",
      photo: "assets/articulo-3.png",
    },
  ],
};
